webappp/eStanica_2017_2018/eStanica.Web/Areas/KorisnikModul/Controllers/RecenzijeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eStanica.Data;
using eStanica.Data.Models;
using eStanica.Web.Areas.KorisnikModul.ViewModels;
using eStanica.Web.Helper;
using eUniverzitet.Web.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eStanica.Web.Areas.KorisnikModul.Controllers
{
    [Autorizacija(klijent:true)]
    [Area("KorisnikModul")]
    public class RecenzijeController : Controller
    {
        ApplicationContext _db;
        public RecenzijeController(ApplicationContext db)
        {
            _db = db;
        }
        //Get all recenstion for one travel
        public IActionResult Index(int RecenzijaId=0)
        {
            if (RecenzijaId != 0)
            {
                Recenzija recenzija = _db.Recenzije.Include(x=>x.Karta.PosjecujeLokacije.Grad).Include(x=>x.Karta.PosjecujeLokacije.Linije.Polazak).FirstOrDefault(x => x.Id == RecenzijaId);
                return PartialView("RecenzijaJedna",recenzija);
            }
            return View();
        }
        //View for all users reservation to make recension
        public IActionResult Ocijeni()
        {
            List<RezervacijeVratiRezervacijeKorisnikaVM> viewmodel = new List<RezervacijeVratiRezervacijeKorisnikaVM>();
            Korisnik k = HttpContext.GetLogiraniKorisnik();

            List<Transakcija> transakcije = _db.Transakcije.Where(x => x.KlijentiId == k.Id).ToList();
            foreach (var item in transakcije)
            {
                RezervacijeVratiRezervacijeKorisnikaVM model = new RezervacijeVratiRezervacijeKorisnikaVM();
                TransakcijaStavke stavke = _db.TransakcijaStavke.FirstOrDefault(x => x.TransakcijaId == item.Id);

                if (stavke != null)
                {
                    Karta kartaKupljena = _db.Karte.Include(x => x.PosjecujeLokacije.Linije.Polazak).Include(x => x.PosjecujeLokacije.Grad).FirstOrDefault(x => x.Id == stavke.KartaId);
                    model.DatumPutovanja = kartaKupljena.datumPutovanja.ToShortDateString();
                    model.PonudaKupljena = kartaKupljena.PosjecujeLokacije.Linije.Polazak.Naziv + "-" + kartaKupljena.PosjecujeLokacije.Grad.Naziv;
                    model.Potroseno = stavke.UkupnaCijena.ToString();
                    model.Kolicina = stavke.Kolicina;
                    model.Aktivna = item.otkazano;
                    model.TransakcijaId = item.Id;
                    model.Polazak = kartaKupljena.PosjecujeLokacije.Linije.vrijemePolaska;

                    //Check if user has already made recension
                    if(_db.Recenzije.LastOrDefault(x=>x.KartaId==kartaKupljena.Id && x.KlijentiId == k.Id) != null)
                    {
                        model.PostojiVecRecenzija = true;
                        model.RecenzijaId = _db.Recenzije.LastOrDefault(x => x.KartaId == kartaKupljena.Id && x.KlijentiId == k.Id).Id;
                    }
                    //Get date of traveleing for recenstion
                    model.DatumKupovine = kartaKupljena.datumPutovanja;
                    viewmodel.Add(model);
                }
            }

            return View("VratiRezervacijeTrenutnogKorisnika2",viewmodel);
        }
        //View for recenstion
        public IActionResult FormaZaOcjenu(int transakcijaId)
        {
            ViewBag.TransakcijaId = transakcijaId;
            return PartialView("_FormaZaOcjenu");
        }
        //Logic for evaluating recension
        [HttpPost]
        public IActionResult FormaOcijeni(int transakcijaId,string Ocjena="", string Opis="")
        {
            //Add new recensation
            Recenzija recenzija = new Recenzija();
            List<TransakcijaStavke> transkacija = _db.TransakcijaStavke.Include(x=>x.Karta).Where(x => x.TransakcijaId == transakcijaId).ToList();
            int RecenzijaID = 0;

            foreach (var item in transkacija)
            {
                recenzija.Karta = item.Karta;
                recenzija.Klijenti = HttpContext.GetLogiraniKorisnik() as Klijenti;
                recenzija.Ocjena = Convert.ToInt32(Ocjena);
                recenzija.Opis = Opis;
                _db.Recenzije.Add(recenzija);
            }
            _db.SaveChanges();
            RecenzijaID = _db.Recenzije.LastOrDefault().Id;

            return Redirect("/KorisnikModul/Recenzije/Index?RecenzijaId=" + RecenzijaID);
        }
    }
}

webappp/eStanica_2017_2018/eStanica.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using eStanica.Data;
using eStanica.Data.Models;
using eStanica.Web.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using eStanica.Data.Helper;
using System.IO;
using eStanica.Web.Helper;
using System.Configuration;
using eStanica.Web.Services;
using Microsoft.Extensions.Options;

namespace eStanica.Web.Controllers
{

    public class LoginController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly IHostingEnvironment _env;
        private readonly IEmailService _emailService;
        private readonly MyConfig _config;

        SelectListItem a1 = new SelectListItem
        {
            Text = "BIH",
            Value = "1"
        };
        SelectListItem a2 = new SelectListItem
        {
            Text = "Srbija",
            Value = "2"
        };
        SelectListItem a3 = new SelectListItem
        {
            Text = "Hrvatska",
            Value = "3"
        };

        public LoginController(ApplicationContext db, IHostingEnvironment env, IEmailService emailService, IOptions<MyConfig>settings)
        {
            _db = db;
            _env = env;
            _emailService = emailService;
            _config = settings.Value;
        }
        //View za logiranje 
        public IActionResult Index()
        {
            return View(new LoginIndexViewModel());
        }
        //Log out logika
        public IActionResult LogOut()
        {
            HttpContext.SetLogiraniKorisnik(null);
            //HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
        public IActionResult AfterLogin()
        {
            return View();
        }
        [HttpPost]
        //View za Verifikovanje statusa klijenta(student, penzioner)-Post
        public IActionResult VerifikacijaStatusa(IFormFile pic, int Korisid)
        {
            if (pic != null)
            {
                var stream = new MemoryStream();
                pic.CopyTo(stream);
                Klijenti k = _db.Klijenti.FirstOrDefault(x => x.Id == Korisid);

                k.slikaIndeksa = stream.ToArray();
                _db.Klijenti.Update(k);
                _db.SaveChanges();

            }
            return Content("snimljeno");
        }
        //View za Verifikovanje statusa klijenta(student, penzioner)-Get
        public IActionResult VerifikacijaStatusa()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            ViewBag.KorisnikIdd = k.Id;

            return View();
        }
        [HttpPost]
        //Logika trazenja korisnika u bazi nakon unosa username i pw u Index Viewu.
        public IActionResult Index(LoginIndexViewModel vm)
        {
            //Trazenje korisnika u bazi

            Korisnik korisnik = new Klijenti();
            korisnik = _db.Korisnici.FirstOrDefault(x => x.username == vm.username && x.password == vm.password);
            if (korisnik != null)
            {
                //Ako je korisnik verifikovao email
                if (korisnik.isValid)
                {
                    HttpContext.SetLogiraniKorisnik(korisnik, vm.Remember);
                    if (korisnik.Zanimanje == "Student" || korisnik.Zanimanje == "Penzioner")
                    {
                        //Castovanje u klijenta 
                        var klijent = korisnik as Klijenti;
                        string zanimanje = klijent.Zanimanje;
                        bool isStudent = false;

                        //Provjera zanimanja i slike
                        isStudent = zanimanje == "Student" ? true : false;
                        if (isStudent)
                        {
                            if (klijent.slikaIndeksa == null)
                            {
                                ViewBag.KorisnikId = korisnik.Id;
                                return PartialView("_Verifikacija");
                            }
                        }
                        else
                        {
                            if (klijent.slikaPenzionerskeKartice == null)
                            {
                                ViewBag.KorisnikId = korisnik.Id;
                                return PartialView("_Verifikacija");
                            }
                        }

                    }
                    return PartialView("_Pocetna");
                }

            }
            return PartialView("_FailureLogin");

        }
        [HttpGet]
        //Sign up view - Get
        public IActionResult SignUp()
        {
            LoginSignUpViewModel vm = new LoginSignUpViewModel();
            vm.Zemlje = new List<SelectListItem>();
            vm.Zemlje.Add(a1);
            vm.Zemlje.Add(a2);
            vm.Zemlje.Add(a3);
            return View(vm);
        }
        public IActionResult Successfull()
        {
            return PartialView();
        }
        [HttpPost]
        //Sign up view - Post
        public IActionResult SignUp2(LoginSignUpViewModel vm)
        {
            List<SelectListItem> zanimanja = Zanimanja.VratiZanimanja();

            if (ModelState.IsValid)
            {
                //Initialise new client
                Klijenti k = new Klijenti();
                k.Ime = vm.Ime;
                k.password = vm.Pw;
                k.Prezime = vm.Prezime;
                k.Spol = vm.Gender[0];
                k.Telefon = vm.Telefon;
                k.username = vm.Username;
                if (vm.OdabranaZemlja == Convert.ToInt32(a1.Value))
                    k.ZemljaPorijekla = a1.Text;
                else if (vm.OdabranaZemlja == Convert.ToInt32(a2.Value))
                    k.ZemljaPorijekla = a2.Text;
                else
                    k.ZemljaPorijekla = a3.Text;
                k.datumRodjenja = vm.DatumRodenja;

                k.Email = vm.Email;
                k.isValid = false;
                foreach (var item in zanimanja)
                {
                    if (vm.odabranoZanimanje == Convert.ToInt32(item.Value))
                        k.Zanimanje = item.Text;
                }
                k.Uloge = _db.Uloge.First();
                _db.Klijenti.Add(k);
                _db.SaveChanges();

                //Email sending
                BuildEmailTemplate(k.Id);
                return PartialView();
            }

            else
            {
                ViewBag.DisableLayout = "DA";
                return View("SignUp", vm);
            }
        }
        public IActionResult Confirm(int regId)
        {
            ViewBag.regId = regId;
            Klijenti klijent = _db.Klijenti.FirstOrDefault(x => x.Id == regId);

            if (klijent != null)
            {
                if(klijent.isValid)
                ViewBag.IsValid = "DA";
            }
            return View();
        }
        public IActionResult RegisterConfirm(int regId)
        {
            //Find user and set him valid in db
            Klijenti k = _db.Klijenti.FirstOrDefault(x => x.Id == regId);
            k.isValid = true;

            _db.Klijenti.Update(k);
            _db.SaveChanges();
            return PartialView();
        }

        public void BuildEmailTemplate(int regId)
        {
            string webRoot = _env.WebRootPath;
            string body = System.IO.File.ReadAllText(webRoot + "/EmailTemplate" + "/Text" + ".cshtml");

            var korisnik = _db.Klijenti.Where(x => x.Id == regId).FirstOrDefault();
            var url = _config.WebHost+"/Confirm?regId=" + regId; 

            body = body.Replace("@ViewBag.ConfirmationLink", url);
            body = body.ToString();

            //Send email using emailService
            _emailService.BuildEmailTemplate("Potvrda korisnickog racuna za autobusku stanicu", body, korisnik.Email);
        }
    }
}

webappp/eStanica_2017_2018/eStanica.Web/Views/Shared/_Layout.cshtml
@using eStanica.Web.Helper

@{
    Korisnik k = Context.GetLogiraniKorisnik();
    @inject ApplicationContext Db

     List<Transakcija> transkacije;

    if (k != null)
    {
        transkacije = Db.Transakcije.Where(x => x.KlijentiId == k.Id).ToList();
    }
    else
    {
        transkacije = new List<Transakcija>();
    }
    }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>eStanica - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/MyCSS.css" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



</head>
<body>
    <div class="container" id="div1">
        <ul id="ul1">
            @if (k == null)
            {
                <li class="li2"><a asp-controller="Login" asp-action="Index"><i class="fa fa-level-up" style="font-size:24px"></i> Log in</a></li>
                <li class="li2"><a asp-controller="Login" asp-action="SignUp"><i class="fa" style="font-size:24px">&#xf090;</i> Sign up</a></li>
            }


            <li id="li1">
                @*<b class="logo">eStanica.com</b>*@
                <a class="logo" style="padding:inherit" asp-controller="Home" asp-action="Index"> <img src="~/images/eStanicalogo.png" height="55" /> </a>
            </li>


            <li><a asp-controller="Home" asp-action="Index"><i class="fa fa-home" style="font-size:24px"></i> Pocetna</a></li>
            @if (k != null)
            {
                if (k.Discriminator == "Klijenti")
                {
                    <li><a asp-controller="Home" asp-action="Travels"><i class="fa fa-bus" style="font-size:24px"></i> Ponude</a></li>
                    <li><i class="fa fa-search" style="font-size:24px;margin-top:15px"></i><a asp-controller="Home" asp-action="Search">Pretraga</a></li>
                    @if (transkacije.Count > 0)
                    {
                        <li><a asp-controller="Rezervacije" asp-action="VratiRezervacijeTrenutnogKorisnika" asp-area="KorisnikModul"><i class="fa fa-list-alt" style="font-size:24px"></i>Moje rezervacije</a></li>
                        <li><a asp-controller="Recenzije" asp-action="Ocijeni" asp-area="KorisnikModul"><i class="fa fa-flag" style="font-size:24px"></i>Ocijeni putovanje </a></li>
                    }
                }
                else
                {
                    <li><i class="fa fa-search" style="font-size:24px;margin-top:15px"></i><a asp-controller="Home" asp-action="Search">Pretraga</a></li>
                    <li><a asp-controller="Home" asp-action="Index" asp-area="UpravnikModul"><i class="fa fa-edit" style="font-size:24px"></i> Administratorski panel</a></li>

                }
                <li class="li2"><i class="glyphicon glyphicon-user"></i><a asp-controller="Login" asp-action="LogOut">Log out - @k.Ime @k.Prezime</a></li>
            }


            @*else
        {
            <li>
                <div id="login">
            <li style="float:right;position:relative;left:25px"><a asp-controller="Login" asp-action="Index"><i class="fa fa-level-up" style="font-size:24px"></i> Log in</a></li>
            <li style="float:right;position:relative;left:45px"><a asp-controller="Login" asp-action="SignUp"><i class="fa" style="font-size:24px">&#xf090;</i> Sign up</a></li>
               </div>
            </li>
        }*@
        </ul>
    </div>
    <div class="container">
        <div class="prevozniciDiv">
            <div class="row oboji" id="prevozniciMain">
                <div class="col-md-5 col-md-offset-1 ">
                    <div id="prevozniciAjax">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="linijeDiv">
            <div class="row oboji" id="LinijeMain">
                <div class="col-md-0 col-md-offset-0 text-center">
                    <div id="linijeAjax">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <div class="footer" id="myFooter">
        <div class="text-center">
            <p></p>
            <p>Copyright &copy; 2017-2020 eStanica web app. All rights reserved</p>
            <p class="kontakt">KONTAKT</p>
            <p>Cassiopeia d.o.o., Sarajevo, BiH</p>
            <p>Adresa: Trg Alije Izetbegovica 1</p>
        </div>


    </div>
    <script src="~/js/user.js"></script>


    @RenderSection("Scripts", required: false)
    <script>
        $(document).ready(function () {

            $.ajax({
                type: "get",
                url: "/KorisnikModul/Prevoznici/Index",
                success: function (data) {
                    $("#prevozniciAjax").html(data);
                }

            });
            $.ajax({
                type: "get",
                url: "/KorisnikModul/Linije/Index",
                success: function (data) {
                    $("#linijeAjax").html(data);

                }

            });

        });

    </script>
</body>
</html>