webappp/eStanica_2017_2018/eStanica.Web/Areas/KorisnikModul/Controllers/LinijeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using eStanica.Data.Models;
using eStanica.Data;
using eStanica.Web.Models;
using Microsoft.EntityFrameworkCore;
using eUniverzitet.Web.Helper;

namespace eStanica.Web.Controllers
{
    //[Autorizacija(klijent: true)]
    [Area("KorisnikModul")]
    public class LinijeController : Controller
    {
        ApplicationContext _db;
        public LinijeController(ApplicationContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var podaci = _db.Linije.Include(x => x.Destinacija)
                .Include(x => x.Polazak)
                .Include(x => x.Prevoznik)
                .Distinct()
                .ToList();
            return PartialView(podaci); 
        }
    }
}

webappp/eStanica_2017_2018/eStanica.Web/Areas/UpravnikModul/Controllers/LokacijeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eStanica.Data;
using eStanica.Data.Models;
using eStanica.Web.Areas.UpravnikModul.ViewModels;
using eStanica.Web.Helper;
using eUniverzitet.Web.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eStanica.Web.Areas.UpravnikModul.Controllers
{
    [Area("UpravnikModul")]
    [Autorizacija(uposlenik: true)]

    public class LokacijeController : Controller
    {
        ApplicationContext _db;
        public LokacijeController(ApplicationContext db)
        {
            _db = db;
        }

        public IActionResult Drzave(string Pretraga)
        {

            List<Drzava> drzave = _db.Drzave
                .Where(x => Pretraga == null || x.Naziv.Contains(Pretraga))
                .ToList();

            if (HttpContext.IsAjax())
                return PartialView(drzave);
            return View(drzave);
        }

        public IActionResult Gradovi(LokacijeGradoviVM VM)
        {
            if (VM.DrzavaId == 0)
                VM.DrzavaId = 1;

            VM.Drzave = _db.Drzave.Select(
                x => new SelectListItem
                {
                    Text = x.Naziv,
                    Value = x.Id.ToString()
                }
                ).ToList();
            VM.Gradovi = _db.Gradovi
                .Where(x => x.DrzavaId == VM.DrzavaId && (VM.Pretraga == null || x.Naziv.Contains(VM.Pretraga)))
                .ToList();

            if(HttpContext.IsAjax())
                return PartialView(VM);
            return View(VM);
        }

        public IActionResult Izbrisi(int Id)
        {
            Grad g = _db.Gradovi.Find(Id);
            _db.Gradovi.Remove(g);
            _db.SaveChanges();

            return Redirect("/UpravnikModul/Lokacije/Gradovi?DrzavaId=" + g.DrzavaId);
        }

        public IActionResult Dodaj_Drzavu()
        {

            if (HttpContext.IsAjax())
                return PartialView();
            return View();
        }

        public IActionResult Uredi_Drzavu(int Id)
        {

            Drzava d = _db.Drzave.Find(Id);

            if (HttpContext.IsAjax())
                return PartialView(d);
            return View(d);
        }

        public  IActionResult SnimiDrzavu(Drzava d)
        {
            Drzava drzava;

            if (d.Id == 0)
            {
                drzava = new Drzava();
                _db.Drzave.Add(drzava);
            }
            else
            {
                drzava = _db.Drzave.Find(d.Id);
            }
                drzava.Naziv = d.Naziv;           

            _db.SaveChanges();

            return RedirectToAction("Drzave");
        }

        public IActionResult IzbrisiDrzavu(int Id)
        {
            List<Grad> gradovi = _db.Gradovi.Where(x => x.DrzavaId == Id).ToList();
            foreach (var x in gradovi)
            {
                _db.Remove(x);
            }

            Drzava d = _db.Drzave.Find(Id);
            _db.Drzave.Remove(d);
            _db.SaveChanges();

            return RedirectToAction("Drzave");
        }
        
        public IActionResult Dodaj_Grad(int drzavaId)
        {
            LokacijeDodajVM VM = new LokacijeDodajVM
            {
                Drzave = _db.Drzave.Select
                (
                    x => new SelectListItem
                    {
                        Text = x.Naziv,
                        Value = x.Id.ToString()
                    }
                 ).ToList(),

                DrzavaId = drzavaId
            };

            if (HttpContext.IsAjax())
                return PartialView(VM);
            return View(VM);
        }

        public IActionResult Uredi_Grad(int Id)
        {
            Grad g = _db.Gradovi.Find(Id);

            if (HttpContext.IsAjax())
                return PartialView(g);
            return View(g);
        }

        public IActionResult SnimiGrad(LokacijeDodajVM VM)
        {
            Grad grad = new Grad
            {
                DrzavaId = VM.DrzavaId,
                Naziv = VM.Naziv
            };

            _db.Gradovi.Add(grad);
            _db.SaveChanges();

            return RedirectToAction("Gradovi", new { DrzavaId = grad.DrzavaId });
        }

        public IActionResult SnimiGrad_(Grad g)
        {
            Grad grad = _db.Gradovi.Find(g.Id);
            grad.Naziv = g.Naziv;

            _db.SaveChanges();

            return RedirectToAction("Gradovi", new { DrzavaId = grad.DrzavaId });
        }

    }
}

webappp/eStanica_2017_2018/eStanica.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using eStanica.Data;
using eStanica.Data.Models;
using eStanica.Web.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using eStanica.Data.Helper;
using System.IO;
using eStanica.Web.Helper;
using System.Configuration;
using eStanica.Web.Services;
using Microsoft.Extensions.Options;

namespace eStanica.Web.Controllers
{

    public class LoginController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly IHostingEnvironment _env;
        private readonly IEmailService _emailService;
        private readonly MyConfig _config;

        SelectListItem a1 = new SelectListItem
        {
            Text = "BIH",
            Value = "1"
        };
        SelectListItem a2 = new SelectListItem
        {
            Text = "Srbija",
            Value = "2"
        };
        SelectListItem a3 = new SelectListItem
        {
            Text = "Hrvatska",
            Value = "3"
        };

        public LoginController(ApplicationContext db, IHostingEnvironment env, IEmailService emailService, IOptions<MyConfig>settings)
        {
            _db = db;
            _env = env;
            _emailService = emailService;
            _config = settings.Value;
        }
        //View za logiranje 
        public IActionResult Index()
        {
            return View(new LoginIndexViewModel());
        }
        //Log out logika
        public IActionResult LogOut()
        {
            HttpContext.SetLogiraniKorisnik(null);
            //HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
        public IActionResult AfterLogin()
        {
            return View();
        }
        [HttpPost]
        //View za Verifikovanje statusa klijenta(student, penzioner)-Post
        public IActionResult VerifikacijaStatusa(IFormFile pic, int Korisid)
        {
            if (pic != null)
            {
                var stream = new MemoryStream();
                pic.CopyTo(stream);
                Klijenti k = _db.Klijenti.FirstOrDefault(x => x.Id == Korisid);

                k.slikaIndeksa = stream.ToArray();
                _db.Klijenti.Update(k);
                _db.SaveChanges();

            }
            return Content("snimljeno");
        }
        //View za Verifikovanje statusa klijenta(student, penzioner)-Get
        public IActionResult VerifikacijaStatusa()
        {
            Korisnik k = HttpContext.GetLogiraniKorisnik();
            ViewBag.KorisnikIdd = k.Id;

            return View();
        }
        [HttpPost]
        //Logika trazenja korisnika u bazi nakon unosa username i pw u Index Viewu.
        public IActionResult Index(LoginIndexViewModel vm)
        {
            //Trazenje korisnika u bazi

            Korisnik korisnik = new Klijenti();
            korisnik = _db.Korisnici.FirstOrDefault(x => x.username == vm.username && x.password == vm.password);
            if (korisnik != null)
            {
                //Ako je korisnik verifikovao email
                if (korisnik.isValid)
                {
                    HttpContext.SetLogiraniKorisnik(korisnik, vm.Remember);
                    if (korisnik.Zanimanje == "Student" || korisnik.Zanimanje == "Penzioner")
                    {
                        //Castovanje u klijenta 
                        var klijent = korisnik as Klijenti;
                        string zanimanje = klijent.Zanimanje;
                        bool isStudent = false;

                        //Provjera zanimanja i slike
                        isStudent = zanimanje == "Student" ? true : false;
                        if (isStudent)
                        {
                            if (klijent.slikaIndeksa == null)
                            {
                                ViewBag.KorisnikId = korisnik.Id;
                                return PartialView("_Verifikacija");
                            }
                        }
                        else
                        {
                            if (klijent.slikaPenzionerskeKartice == null)
                            {
                                ViewBag.KorisnikId = korisnik.Id;
                                return PartialView("_Verifikacija");
                            }
                        }

                    }
                    return PartialView("_Pocetna");
                }

            }
            return PartialView("_FailureLogin");

        }
        [HttpGet]
        //Sign up view - Get
        public IActionResult SignUp()
        {
            LoginSignUpViewModel vm = new LoginSignUpViewModel();
            vm.Zemlje = new List<SelectListItem>();
            vm.Zemlje.Add(a1);
            vm.Zemlje.Add(a2);
            vm.Zemlje.Add(a3);
            return View(vm);
        }
        public IActionResult Successfull()
        {
            return PartialView();
        }
        [HttpPost]
        //Sign up view - Post
        public IActionResult SignUp2(LoginSignUpViewModel vm)
        {
            List<SelectListItem> zanimanja = Zanimanja.VratiZanimanja();

            if (ModelState.IsValid)
            {
                //Initialise new client
                Klijenti k = new Klijenti();
                k.Ime = vm.Ime;
                k.password = vm.Pw;
                k.Prezime = vm.Prezime;
                k.Spol = vm.Gender[0];
                k.Telefon = vm.Telefon;
                k.username = vm.Username;
                if (vm.OdabranaZemlja == Convert.ToInt32(a1.Value))
                    k.ZemljaPorijekla = a1.Text;
                else if (vm.OdabranaZemlja == Convert.ToInt32(a2.Value))
                    k.ZemljaPorijekla = a2.Text;
                else
                    k.ZemljaPorijekla = a3.Text;
                k.datumRodjenja = vm.DatumRodenja;

                k.Email = vm.Email;
                k.isValid = false;
                foreach (var item in zanimanja)
                {
                    if (vm.odabranoZanimanje == Convert.ToInt32(item.Value))
                        k.Zanimanje = item.Text;
                }
                k.Uloge = _db.Uloge.First();
                _db.Klijenti.Add(k);
                _db.SaveChanges();

                //Email sending
                BuildEmailTemplate(k.Id);
                return PartialView();
            }

            else
            {
                ViewBag.DisableLayout = "DA";
                return View("SignUp", vm);
            }
        }
        public IActionResult Confirm(int regId)
        {
            ViewBag.regId = regId;
            Klijenti klijent = _db.Klijenti.FirstOrDefault(x => x.Id == regId);

            if (klijent != null)
            {
                if(klijent.isValid)
                ViewBag.IsValid = "DA";
            }
            return View();
        }
        public IActionResult RegisterConfirm(int regId)
        {
            //Find user and set him valid in db
            Klijenti k = _db.Klijenti.FirstOrDefault(x => x.Id == regId);
            k.isValid = true;

            _db.Klijenti.Update(k);
            _db.SaveChanges();
            return PartialView();
        }

        public void BuildEmailTemplate(int regId)
        {
            string webRoot = _env.WebRootPath;
            string body = System.IO.File.ReadAllText(webRoot + "/EmailTemplate" + "/Text" + ".cshtml");

            var korisnik = _db.Klijenti.Where(x => x.Id == regId).FirstOrDefault();
            var url = _config.WebHost+"/Confirm?regId=" + regId; 

            body = body.Replace("@ViewBag.ConfirmationLink", url);
            body = body.ToString();

            //Send email using emailService
            _emailService.BuildEmailTemplate("Potvrda korisnickog racuna za autobusku stanicu", body, korisnik.Email);
        }
    }
}

webappp/eStanica_2017_2018/eStanica.Web/Areas/UpravnikModul/Views/Shared/_LayoutUpravnik.cshtml
@using eStanica.Web.Helper

@{
    Korisnik k = Context.GetLogiraniKorisnik();
    var controller = ViewContext.RouteData.Values["Controller"];
    var action = Funkcije.FirstCharToUpper(ViewContext.RouteData.Values["Action"].ToString().Replace("_", " "));
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>eStanica</title>

    <!-- Bootstrap core CSS-->
    <link href="/upravnik/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Custom fonts for this template-->
    <link href="/upravnik/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Page level plugin CSS-->
    <link href="/upravnik/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/upravnik/css/sb-admin.css" rel="stylesheet">
    <link href="~/upravnik/css/UpravnikCSS.css" rel="stylesheet" />

</head>

<body id="page-top">

    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

        <a class="navbar-brand mr-1" asp-area="" asp-controller="Home" asp-action="Index">eStanica.com</a>

        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>

        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Traži..." aria-label="Search" aria-describedby="basic-addon2" name="pretraga">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>

        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">


            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i> @k.Ime @k.Prezime
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" asp-controller="Korisnici" asp-action="Profil">Postavke profila</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item" data-toggle="modal" data-target="#logoutModal">Logout</a>
                </div>
            </li>
        </ul>

    </nav>

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item">
                <a asp-controller="Home" asp-action="Index" class="nav-link">
                    <i class="fas fa-fw fa-home"></i>
                    <span>Početna</span>
                </a>

            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-fw fa-map-marker"></i>
                    <span>Lokacije</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                    <ul class="nav nav-second-level">

                        <li><a asp-controller="Lokacije" asp-action="Drzave">Drzave</a></li>
                        <li><a asp-controller="Lokacije" asp-action="Gradovi">Gradovi</a></li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a asp-controller="Prevoznici" asp-action="Prikaz" class="nav-link">
                    <i class="fas fa-fw fa-bus-alt"></i>
                    <span>Prevoznici</span>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Linije" asp-action="Prikaz" class="nav-link">
                    <i class="fas fa-fw fa-road"></i>
                    <span>Linije</span>
                </a>
            </li>
            @if (k.UlogeId == 4)
            {
                <li class="nav-item">
                    <a asp-controller="Korisnici" asp-action="Prikazi" class="nav-link">
                        <i class="fas fa-fw fa-user-friends"></i>
                        <span>Korisnici</span>
                    </a>
                </li>
            }
            <li class="nav-item">
                <a asp-controller="Korisnici" asp-action="Profil" asp-route-Id="" class="nav-link">
                    <i class="fas fa-fw fa-user"></i>
                    <span>Postavke profila</span>
                </a>
            </li>
            <li class="nav-item">
                <a asp-area="" asp-controller="Login" asp-action="Logout" class="nav-link">
                    <i class="fas fa-fw fa-sign-out-alt"></i>
                    <span>Odjava</span>
                </a>
            </li>
        </ul>

        <div id="content-wrapper">

            <div class="container-fluid">

                <!-- Breadcrumbs-->
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a asp-controller="Home" asp-action="Index" ajax-poziv="da" ajax-rezultat="ajaxDiv"><i class="fa fa-home"></i> Upravnik</a>
                        @if (!controller.Equals("Home"))
                        {
                            <span> / @controller / @action</span>
                        }
                    </li>
                </ol>

                <!-- Page Content -->
                <div class="col-lg-12" id="ajaxDiv">
                    @RenderBody()
                </div>

            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Kani © eStanica 2019</span>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Želite se odjaviti?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Jeste li sigurni da se želite odjaviti iz trenutne sesije?</div>
                <div class="modal-footer">
                    <button class="btn btn-outline-secondary" type="button" data-dismiss="modal">Prekid</button>
                    <a class="btn btn-outline-danger" asp-controller="Login" asp-action="LogOut" asp-area="">Odjava</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="/upravnik/vendor/jquery/jquery.min.js"></script>
    <script src="/upravnik/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/upravnik/vendor/jquery-easing/jquery.easing.min.js"></script>


    <!-- Validacija -->
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>


    <!-- Custom scripts for all pages-->
    <script src="/upravnik/js/sb-admin.js"></script>

</body>

</html>

webappp/eStanica_2017_2018/eStanica.Web/Areas/UpravnikModul/Views/Shared/_LayoutUpravnik_1.cshtml
@using eStanica.Web.Helper

@{
    Korisnik k = Context.GetLogiraniKorisnik();
}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>eStanica - @ViewData["Title"]</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/upravnik/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="~/upravnik/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/upravnik/dist/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/upravnik/dist/css/UpravnikCSS.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/upravnik/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">eStanica.com</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> @k.Ime @k.Prezime <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a asp-controller="Login" asp-action="LogOut" asp-area=""><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-light" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a asp-controller="Home" asp-action="Index" ajax-poziv="da" ajax-rezultat="ajaxDiv"><i class="fa fa-home"></i> Početna</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-map-marker"></i> Lokacije<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a asp-controller="Lokacije" asp-action="Drzave" ajax-poziv="da" ajax-rezultat="ajaxDiv">Drzave</a>
                                </li>
                                <li>
                                    <a asp-controller="Lokacije" asp-action="Gradovi" ajax-poziv="da" ajax-rezultat="ajaxDiv">Gradovi</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a asp-controller="Korisnici" asp-action="Korisnici"><i class="fa fa-user"></i> Korisnici</a>
                        </li>

                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12" id="ajaxDiv">
                        @RenderBody()
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/upravnik/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/upravnik/vendor/bootstrap/js/bootstrap.min.js"></script>


    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/upravnik/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/upravnik/dist/js/sb-admin-2.js"></script>
    <script src="~/js/jsFIT.js"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>