webappp/eStanica_2017_2018/eStanica.Web/Areas/KorisnikModul/Controllers/RezervacijeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eStanica.Data;
using eStanica.Data.Helper;
using eStanica.Data.Models;
using eStanica.Web.Areas.KorisnikModul.ViewModels;
using eStanica.Web.Helper;
using eStanica.Web.Services;
using eUniverzitet.Web.Helper;
using Ispit.Web.Helper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eStanica.Web.Areas.KorisnikModul.Controllers
{
    [Area("KorisnikModul")]
    [Autorizacija(klijent:true)]
    public class RezervacijeController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly IEmailService _emailService;

        public RezervacijeController(ApplicationContext db, IEmailService emailService)
        {
            _db = db;
            _emailService = emailService;
        }
        //View to make reservation at specified date and type of card pick
        public IActionResult Index(int PonudId,string tipKarte="")
        {
            if (string.IsNullOrEmpty(tipKarte))
                ViewBag.NemaKarte = "DA";

            ViewBag.PonudId = PonudId;
            ViewBag.TipKarte = tipKarte;
            return View();
        }
        //Check if place in buses are occupied or free
        [HttpPost]
        public IActionResult ProvjeraMjesta(DateTime Datum, int PonudId, string TipKarte="")
        {
            RezervacijeProvjeraMjestaVM model = new RezervacijeProvjeraMjestaVM();

            HttpContext.Session.SetString("PonudaId", PonudId.ToString());

            MySessionExtensions.Set<DateTime>(HttpContext.Session, "DatumRezervacije", Datum);

            HttpContext.Session.SetString("TipKarte", TipKarte);

            var podaci = _db.PosjecujeLokacije.Include(x => x.Linije.Autobus).FirstOrDefault(x => x.Id == PonudId);
            
            //Get occupied places in bus
            var brojZauzetihMjesta = _db.Karte.Where(x => x.datumPutovanja == Datum && x.PosjecujeLokacije.LinijeId == podaci.LinijeId).ToList();
            foreach (var item in brojZauzetihMjesta)
            {
                model.ZauzetaMjesta.Add(Convert.ToInt32(item.brojSjedista));
            }
            //Initialise model
            model.UkupanBrojMjestaAutobusa = podaci.Linije.Autobus.brojSjedistaBusa;
            model.BrojZauzetihMjesta = brojZauzetihMjesta.Count();
            model.BrojSlobodnihMjesta = model.UkupanBrojMjestaAutobusa - model.BrojZauzetihMjesta;
            
            return View(model);
        }

        //Make reservation of cards
        [HttpPost]
        public IActionResult DodajRezervaciju(RezervacijePrikazFormePlacanjeVM model)
        {
            Korisnik logirani = HttpContext.GetLogiraniKorisnik();

            if (string.IsNullOrEmpty(model.BrojKreditneKartice))
                return Content("niste unijeli kreditnu karticu");
            
            //Add new credit card 
            Kartica novaKartica = new Kartica
            {
                BrojKartice = model.BrojKreditneKartice,
                Klijenti = (Klijenti)logirani,
                SredstvoPlacanjaId = 1,
                Banka = Banke.VratiBanke().Find(x => x.Value == model.OdabranaBankaId.ToString()).Text,
            };
            _db.Kartice.Add(novaKartica);

            //Picked reservation travels
            var ponudaRezervacije = _db.PosjecujeLokacije.Include(x=>x.Linije)
                .FirstOrDefault(x => x.Id == Convert.ToInt32(HttpContext.Session.GetString("PonudaId")));

            //Crete new transaction of cards
            var transakcijaNova = new Transakcija();
            transakcijaNova.brojTransakcije = "1";
            transakcijaNova.datumKupovine = DateTime.Now;
            transakcijaNova.otkazano = false;
            transakcijaNova.Status = "zaprimljena";
            transakcijaNova.Klijenti = (Klijenti)logirani;
            transakcijaNova.Kartica = novaKartica;

            TransakcijaStavke stavkeTransakcije = new TransakcijaStavke();

            //Add new transaction of cards in database
            foreach (var item in model.ProsliModel.Mjesta)
            {
                Karta karta = new Karta();

                stavkeTransakcije.Karta = karta;
                stavkeTransakcije.Kolicina = model.ProsliModel.Mjesta.Count;
                stavkeTransakcije.Transakcija = transakcijaNova;

                if (model.UkupnaCijenaPopust == 0)
                {
                    stavkeTransakcije.UkupnaCijena = model.UkupnaCijena;
                }
                else
                {
                    stavkeTransakcije.UkupnaCijena = model.UkupnaCijenaPopust;
                }

                karta.PosjecujeLokacije = ponudaRezervacije;
                karta.Aktivna = true;
                karta.brojSjedista = item.ToString();
                karta.BrojKarte = "XXX-123";
                karta.datumPutovanja = MySessionExtensions.Get<DateTime>(HttpContext.Session, "DatumRezervacije");

                //karta.datumPutovanja = new DateTime(Convert.ToInt32(godina[0]), Convert.ToInt32(razdvojeniDatum[1]), Convert.ToInt32(razdvojeniDatum[0]));
                karta.TipKarte = _db.TipoviKarte.FirstOrDefault(x => x.Tip == HttpContext.Session.GetString("TipKarte"));

                _db.Karte.Add(karta);
            }
            _db.TransakcijaStavke.Add(stavkeTransakcije);
            _db.SaveChanges();

            //Send user a email
            string bodyText = "Poštovani Uspješno ste platili rezervaciju za ponudu " + ponudaRezervacije.Linije.Naziv + " u iznosu od " + stavkeTransakcije.UkupnaCijena + "na dan " + transakcijaNova.datumKupovine.ToShortDateString() + " Pozdrav Vaša autobuska stanica";
            _emailService.BuildEmailTemplate("Potvrda  o uspješnosti rezervacije", bodyText, logirani.Email);

            return Content("Rezervacija uspjesno provedena");
        }
        //Form for paying
        public IActionResult PrikazFormeZaPlacanje([FromBody]RezervacijaMjestaJson Model)
        {
            var ponudaRezervacije = _db.PosjecujeLokacije
                .FirstOrDefault(x => x.Id == Convert.ToInt32(HttpContext.Session.GetString("PonudaId")));

            //Initializing model
            RezervacijePrikazFormePlacanjeVM viewmodel = new RezervacijePrikazFormePlacanjeVM();
            viewmodel.Banke = Banke.VratiBanke();
            viewmodel.Karte = Kartice.VratiKartice();
            viewmodel.KolicinaKarata = Model.Mjesta.Count.ToString();
            viewmodel.ProsliModel = Model;
            viewmodel.PostojiPopustNaLiniji = _db.PopustNaLiniji.FirstOrDefault(x => x.LinijeId == ponudaRezervacije.LinijeId) != null ? true : false;
            //Check for expiracy
            viewmodel.DatumRezervacije = MySessionExtensions.Get<DateTime>(HttpContext.Session, "DatumRezervacije");

            if (viewmodel.PostojiPopustNaLiniji)
            {
                viewmodel.IstekaoDatumPopusta = _db.PopustNaLiniji.Include(x => x.Popust).FirstOrDefault(x => x.LinijeId == ponudaRezervacije.LinijeId).Popust.DatumVazenjaPopusta > viewmodel.DatumRezervacije ? true : false;
            }
            //Get total spent that user ordered
            foreach (var item in Model.Mjesta)
            {
                viewmodel.UkupnaCijena += _db.PosjecujeLokacije
                .FirstOrDefault(x => x.Id == Convert.ToInt32(HttpContext.Session.GetString("PonudaId"))).cijenaOdPolaska;
                viewmodel.MjestaOdabrana.Add(item);
            }

            //Type of card user picked, travel that he reserved.
            viewmodel.TipKarte = _db.TipoviKarte.FirstOrDefault(x => x.Tip == HttpContext.Session.GetString("TipKarte")).Tip;
            viewmodel.PonudaOdabrana = _db.PosjecujeLokacije.Include(x=>x.Linije.Polazak)
                .Include(x=>x.Grad)
                .FirstOrDefault(x => x.Id == Convert.ToInt32(HttpContext.Session.GetString("PonudaId")));

            return View(viewmodel);
        }
        //Generating code coupon for discount
        public IActionResult GenerisiKod()
        {
            //Generate random code coupon
            string code = Convert.ToBase64String(Guid.NewGuid().ToByteArray()).Substring(0, 6);

            var ponudaRezervacije = _db.PosjecujeLokacije
               .FirstOrDefault(x => x.Id == Convert.ToInt32(HttpContext.Session.GetString("PonudaId")));

            //Set coupon code and discount %
            HttpContext.Session.SetString("code", code);
            HttpContext.Session.SetString("discount", _db.PopustNaLiniji.Include(x=>x.Popust).FirstOrDefault(x=>x.LinijeId==ponudaRezervacije.LinijeId).Popust.Postotak.ToString());
            
            //Send email
            string bodyText = "Postovani vaš kod za uračunavanje popusta je" + code;
            _emailService.BuildEmailTemplate("Kod za uračunavanje popusta na cijenu.", bodyText, HttpContext.GetLogiraniKorisnik().Email);

            return Content("Mail uspjesno poslan sa kodom");
        }
        //Checking validity of code
        public IActionResult ProvjeriValidnostKoda(string code)
        {
            var datumRezervacije = MySessionExtensions.Get<DateTime>(HttpContext.Session, "DatumRezervacije");

            //Check for coupon expiracy
            var ponuda = _db.PosjecujeLokacije.FirstOrDefault(x => x.Id == Convert.ToInt32(HttpContext.Session.GetString("PonudaId")));
            var popust = _db.PopustNaLiniji.Include(x=>x.Popust).FirstOrDefault(x => x.LinijeId == ponuda.LinijeId);

            DateTime datum = datumRezervacije;

            if (HttpContext.Session.GetString("code").Equals(code.Trim()) && datum<popust.Popust.DatumVazenjaPopusta)
            {
                HttpContext.Session.SetString("code", "");
                return Content("Kod je validan");
            }
            return Content("Nevalidan kod");
        }
        //Get all transactions-reservations

webappp/eStanica_2017_2018/eStanica.Web/Areas/KorisnikModul/Views/Rezervacije/Index.cshtml
@{
    ViewData["Title"] = "Index";
    string imaKarte = ViewBag.NemaKarte != "" ? ViewBag.NemaKarte : "";
}


<div class="col-md-offset-2" style="margin-top:25px">
    <h2 class="bijelo">Provjera slobodnih mjesta - odredjenog datuma</h2>
    @if (string.IsNullOrEmpty(imaKarte))
    {
        <form asp-action="ProvjeraMjesta" asp-controller="Rezervacije" method="post" id="formaZaProvjeru">
            <div class="form-group">
                <span style="font-size:19px"><b>Unesite datum rezervacije putovanja</b></span>
                <input type="date" id="pickerDate" required="required" name="Datum" />
                <input type="hidden" value="@ViewBag.PonudId" name="PonudId" />
                <input type="hidden" value="@ViewBag.TipKarte" name="TipKarte" />
                <input type="submit" value="Provjeri slobodna mjesta u busu" class="btn btn-success" />
            </div>
        </form>
    }
    else
    {
        <form asp-action="ProvjeraMjesta" asp-controller="Rezervacije">
            <span style="font-size:19px"><b>Unesite datum rezervacije putovanja</b></span>
            <input type="date" id="pickerDate" required="required" name="Datum" />
            <input type="hidden" value="@ViewBag.PonudId" name="PonudId" />
            <br />
            <span style="font-size:19px"><b>Unesite tip karte</b></span>

            <select name="TipKarte">
                <option value="Studentska">Studentska</option>
                <option value="Obicna">Obicna</option>
            </select>
            <br />
            <input type="submit" value="Provjeri slobodna mjesta u busu" class="btn btn-success" style="margin:20px" />
        </form>
    }
</div>
<script>

</script>

webappp/eStanica_2017_2018/eStanica.Web/Areas/KorisnikModul/Views/Rezervacije/PrikazFormeZaPlacanje.cshtml
@model RezervacijePrikazFormePlacanjeVM
@{
    ViewData["Title"] = "PrikazFormeZaPlacanje";
    @inject IHttpContextAccessor HttpContextAccessor
    Layout = null;
}
<style>
    body {
        overflow-y: scroll;
    }
</style>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery/toastr.min.js"></script>
<link rel="stylesheet" href="~/lib/jquery/toastr.min.css" />

<h2 class="bijelo">Forma za placanje - kupujte preko nas :: vasa eStanica.com</h2>
<form asp-action="DodajRezervaciju" asp-controller="Rezervacije" id="payForm">
    <h4>Vasa odabrana ponuda :: <em>@Model.PonudaOdabrana.Linije.Polazak.Naziv - @Model.PonudaOdabrana.Grad.Naziv</em></h4>
    <h4>
        Vasa odabrana mjesta su : @foreach (var item in Model.MjestaOdabrana)
        {
            <span><em>@item ,</em></span>
        }
    </h4>
    <div style="float:right">
        @if (Model.PostojiPopustNaLiniji)
        {
            @if (Model.IstekaoDatumPopusta)
            {
                <div id="showCode" style="display:normal">
                    <h5><em class="bijelo">Posto na ovoj ponudi postoji popust mozete generisati kod za popust - kod dobivate na email </em></h5>
                    <a class="btn btn-success" onclick="Generisi()"><i class="fa fa-lightbulb" style="font-size:24px"></i>Generisi</a>
                </div>
                <div id="afterCode" style="display:none">
                    <input name="code" class="form-control" id="codeId" placeholder="Unesite generisani kod" />
                    <button id="codeSubmit" class="btn btn-success">Provjeri kod</button>
                </div>
            }
        }
    </div>
    @for (int i = 0; i < Model.ProsliModel.Mjesta.Count; i++)
    {
        <input asp-for="ProsliModel.Mjesta[i]" hidden="hidden" />
    }
    <input asp-for="UkupnaCijena" hidden="hidden" />
    <input asp-for="DatumRezervacije" hidden="hidden" />

    <h4>Kolicina karata kupljenih :: <em>@Model.KolicinaKarata</em></h4>
    <h4>Ukupna cijena za platiti u KM :: <em id="fullPrice">@Model.UkupnaCijena KM</em></h4>

    <h4 style="display:none" id="headingForShowPrice">Ukupna cijena za platiti u KM sa popustom :: <em id="showPrice"></em></h4>

    <h4>Tip karte :: <em>@Model.TipKarte</em></h4>
    <h4>Datum rezervacije :: <em>@Model.DatumRezervacije.ToShortDateString()</em> </h4>
    <div class="form-group">
        <span>Banka:</span>
        <select class="form-control" asp-for="OdabranaBankaId" asp-items="@Model.Banke"></select>
        <br />
        <span>Tip karte za placanje</span>
        <select asp-for="OdabranaKartaId" asp-items="@Model.Karte" class="form-control"></select>
    </div>
    <div class="form-group">
        <span>Broj kreditne kartice</span>
        <input asp-for="BrojKreditneKartice" placeholder="Unesite broj karte" class="form-control" required="required" />
    </div>
    <div class="form-group">
        <a class="btn btn-block" id="paySubmit">
            <i class="fa fa-money" style="font-size:24px">Plati</i>
        </a>
    </div>
</form>

<script>
    
    $("#paySubmit").click(function () {
        //If user sent all data
        var forma = $("#payForm");
        var podaci = forma.serialize();

        $.ajax({
            type: "post",
            url: "/KorisnikModul/Rezervacije/DodajRezervaciju",
            data: podaci,
            success: function (data) {
                var podaci = data;

                if (podaci != "niste unijeli kreditnu karticu") {
                    toastr.success(data);
                    location.href = "/KorisnikModul/Rezervacije/VratiRezervacijeTrenutnogKorisnika";
                }
                else {
                    toastr.error(data);
                }
            }
        });
    });

    //Function to generate coude cupon
    function Generisi() {
        $.ajax({
            type: "get",
            url: "/KorisnikModul/Rezervacije/GenerisiKod",
            success: function (data) {
                toastr.success(data);
                $("#showCode").hide();
                $("#afterCode").show();
            }
        });
    }
    //Funtion to validate code coupon
    $("#codeSubmit").click(function () {
        var code = $("#codeId");
        $.ajax({
            type: "get",
            url: "/KorisnikModul/Rezervacije/ProvjeriValidnostKoda?code=" + code.val(),
            success: function (data) {
                if (data != "Nevalidan kod")
                {
                    toastr.success("Kod je ispravan, imate pravo popusta" + data + "%");
                    var priceWithoutDiscount = parseInt($("#fullPrice").html());
                    var priceWithDiscount = priceWithoutDiscount - priceWithoutDiscount / (100 / parseInt(data));
                    $("#afterCode").hide();
                    $("#showPrice").html(priceWithDiscount)
                    $("#headingForShowPrice").show();
                }
                else
                    toastr.error(data);
            }
        });
    });
</script>

webappp/eStanica_2017_2018/eStanica.Web/Areas/KorisnikModul/Views/Rezervacije/ProvjeraMjesta.cshtml
@model RezervacijeProvjeraMjestaVM
@{
    ViewData["Title"] = "ProvjeraMjesta";
    List<int> svaMjestaBusa = new List<int>();
    for (int i = 0; i < Model.UkupanBrojMjestaAutobusa; i++)
    {
        svaMjestaBusa.Add(i);
    }
}

<div style="margin-top:120px;margin-left:120px;color:white;border-bottom:2px dashed steelblue" id="SjedistaDiv">
    <h2 class="bijelo">Odaberite sjediste/a : <span>(X)-zauzeto mjesto vec od prije, (DA) - vase odabrano mjesto</span></h2> 
    <div id="left"><h3>LIJEVA STRANA BUSA</h3></div>
    <div id="right"><h3>DESNA STRANA BUSA</h3></div>
    <br />
    <div class="text-center">
        <a class="btn btn-success" onclick="Pokaz()"><i style="font-size:24px" class="fa fa-money" ></i>Rezervisi</a>
    </div>
</div>

<script>
    if(!nizCekiranihBrojeva)
    var nizCekiranihBrojeva = [];

    function Pokaz() {
        var jsonObject = {
            "Mjesta": nizCekiranihBrojeva
        }; 
        if (nizCekiranihBrojeva.length == 0) {
            alert("Niste odabrali nijedno mjesto");
            location.reload();
        }
        //Sending reserved places in bus to controller
        $.ajax({
            type: "post",
            url: "/KorisnikModul/Rezervacije/PrikazFormeZaPlacanje",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(jsonObject),
            success: function (data) {
                $("#SjedistaDiv").html(data);
            }
        });
    }

    $(document).ready(function () {
        $("#myFooter").hide();
        $("#prevozniciAjax").hide();
        $("#prevozniciMain").hide();
        $("#LinijeMain").hide();
        $("#linijeAjax").hide();
    });
    @for (int i = 0; i < Model.UkupanBrojMjestaAutobusa; i++)
    {
        <text>
       //Regular node available place in bus
       var node = document.createElement("span");
      var to = document.createTextNode(@i);
      node.className = "templateZaMjesta";
      node.id = "n"+@i;
       node.appendChild(to);

       //Occupied place in bus
       var xNode = document.createElement("span");
       var toXNode = document.createTextNode("X");
       toXNode.className = "templateZaMjesta";
       xNode.appendChild(toXNode);
        </text>

      

        if (i%2==0)
        {
            <text>
            $("#left").append(node);
            </text>
        }
        else if(i%2!=0 )
        {
            <text>
            $("#right").append(node);
             </text>
        }
    }
    
    //Mark occuppied place by X
    @for (int j = 0; j < Model.ZauzetaMjesta.Count; j++)
    {
        if (svaMjestaBusa.Contains(Model.ZauzetaMjesta[j]))
        {
            var indeksOf = svaMjestaBusa.IndexOf(Model.ZauzetaMjesta[j]);
            <text>
    $("#n" + @indeksOf).html("X");
            </text>
        }
    }

    //On click left side of bus , make it occupied
    var leftSide = document.getElementById("left");
    var innerLeftSide = leftSide.getElementsByClassName("templateZaMjesta");
    for (var i = 0; i < innerLeftSide.length; i++) {
        innerLeftSide[i].addEventListener("click", function () {
            if (this.innerHTML == "X") {
                alert("Mesto je vec zauzeto");
                location.reload();
            }
            var prosliBroj = this.innerHTML;
            nizCekiranihBrojeva.push(prosliBroj);
           this.innerHTML = "DA";
        });
    }

    //On click right side of bus , make it occupied
    var rightSide = document.getElementById("right");
    var innerRightSide = rightSide.getElementsByClassName("templateZaMjesta");
    for (var i = 0; i < innerRightSide.length; i++) {
        innerRightSide[i].addEventListener("click", function () {
            if (this.innerHTML == "X") {
                alert("Mesto je vec zauzeto");
                location.reload();
            }
            var prosliBroj = this.innerHTML;
            nizCekiranihBrojeva.push(prosliBroj);
            this.innerHTML = "DA";
        });
    }
</script>

webappp/eStanica_2017_2018/eStanica.Web/Areas/KorisnikModul/Views/Rezervacije/VratiRezervacijeTrenutnogKorisnika.cshtml
@model List<RezervacijeVratiRezervacijeKorisnikaVM>
@{
    ViewData["Title"] = "Moje rezervacije";
    int counter = 1;
}
<br />
<script src="~/lib/jquery/toastr.min.js"></script>
<link rel="stylesheet" href="~/lib/jquery/toastr.min.css" />
<style>
 
</style>
<div id="ajaxRezervacije">
    <div>
        <div class="row bijelo">
            <div class="col-md-4 col-md-offset-1">
                @foreach (var item in Model)
                {
                <div class="RezervacijskiDiv" id="@counter">
                    <h3>@(counter++) .</h3>
                    <h4>Datum putovanja:: @item.DatumPutovanja u :: @item.Polazak - sati</h4>
                    <h4>Aktivna rezervacija:: @(item.Aktivna == false ? "DA" : "NE") <button class="btn btn-danger" onclick="Otkazi(@item.TransakcijaId)">Otkazi rezervaciju</button></h4>
                    <h4>Vi putujete na relaciji:: @item.PonudaKupljena</h4>
                    <h4>Platili ste:: @item.Potroseno KM</h4>
                    <h4>Kupili ste karata:: @item.Kolicina</h4>
                </div>

                    <div>-----------------------------------------------</div>
                }
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#myFooter").hide();
        $("#prevozniciAjax").hide();
        $("#prevozniciMain").hide();
        $("#LinijeMain").hide();
        $("#linijeAjax").hide();
    });
    function Otkazi(transakcijaId) {
        if (confirm("Da li zelite otkazati rezervaciju")) {
            $.ajax({
                type: "get",
                url: "/KorisnikModul/Rezervacije/IzbrisiRezervaciju?transakcijaId=" + transakcijaId,
                success: function (data) {
                    $("#ajaxRezervacije").html(data);
                }
            });
        }
    }
</script>